[platformio]
default_envs = uno
src_dir = .

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
; Include the .ino.cpp file generated during Arduino sketch conversion.
build_src_filter = +<tool_shelf.ino*>
