[raspis]
pi01 ansible_host=132.180.196.167 ansible_port=4022 ansible_user=guest ansible_password=TH101Guest2025 ansible_become_password=TH101Guest2025
pi02 ansible_host=132.180.196.167 ansible_port=4024 ansible_user=guest ansible_password=TH101Guest2025 ansible_become_password=TH101Guest2025
pi03 ansible_host=132.180.196.167 ansible_port=4025 ansible_user=guest ansible_become_password=TH101Guest2025
pi04 ansible_host=132.180.196.167 ansible_port=4026 ansible_user=guest ansible_become_password=TH101Guest2025

[raspis:vars]
ansible_become=true
ansible_become_method=sudo
ansible_ssh_private_key_file=~/.ssh/id_ed25519
