import json
import logging
from pathlib import Path
from typing import Callable, Optional

logger = logging.getLogger(__name__)


class Classifier:
    def __init__(
        self,
        thresholds_file: str = "thresholds.json",
        mapping_file: str = "cluster_activity_mapping.json",
        on_classified: Optional[Callable[[dict], Optional[dict]]] = None,
        output_file: Optional[str] = "classified_segments.jsonl",
    ):
        self.thresholds = self._load_thresholds(thresholds_file)
        self.delta_per_unit = self.thresholds["thresholds"][0].get(
            "delta_per_unit", None
        )
        self.mapping = self._load_mapping(mapping_file)
        self.on_classified = on_classified
        self._last_median = None

        self._out_file = None
        if output_file:
            self._out_file = open(output_file, "a")

    def _load_thresholds(self, filepath: str) -> dict:
        """load thresholds from JSON."""
        path = Path(filepath)
        if not path.exists():
            raise FileNotFoundError(
                f"{filepath} not found. Please use cluster.py first."
            )

        with open(path) as f:
            thresholds = json.load(f)

        logger.info(
            f"thresholds loaded: {len(thresholds['clusters'])} Cluster, "
            f"Features: {thresholds['feature_keys']}"
        )
        return thresholds

    def _load_mapping(self, filepath: str) -> dict:
        """mapping cluster-ID -> Activity mapping"""
        path = Path(filepath)
        if not path.exists():
            # if mapping file does not exist yet -> generated by this code
            cluster_ids = [c["cluster_id"] for c in self.thresholds["clusters"]]
            template = {str(cids): f"REPLACE_ME_cluster{cids}" for cids in cluster_ids}
            with open(path, "w") as f:
                json.dump(template, f, indent=2)
            mapping = template
        else:
            with open(path) as f:
                mapping = json.load(f)

        if self.delta_per_unit is None:
            cluster_ids = {c["cluster_id"] for c in self.thresholds["clusters"]}
            mapping_ids = {int(k) for k in mapping.keys()}
            if cluster_ids != mapping_ids:
                template = {
                    str(cids): f"REPLACE_ME_cluster{cids}" for cids in cluster_ids
                }
                with open(path, "w") as f:
                    json.dump(template, f, indent=2)
                mapping = template
                logger.warning("Warning: Cluster-IDs changed - mapping regenerated")

        # normalise keys to int
        mapping = {int(k): v for k, v in mapping.items()}
        logger.info(f"loaded mapping: {mapping}")
        return mapping

    def _nearest_cluster(self, segment: dict) -> int:

        feature_keys = self.thresholds["feature_keys"]
        clusters = self.thresholds["clusters"]

        segment_features = [segment[k] for k in feature_keys]

        min_dist = float("inf")
        nearest = 0

        for cluster in clusters:
            centroid = [cluster["centroid"][k] for k in feature_keys]
            dist = sum((a - b) ** 2 for a, b in zip(segment_features, centroid)) ** 0.5
            if dist < min_dist:
                min_dist = dist
                nearest = cluster["cluster_id"]

        return nearest

    def classify(self, segment: dict) -> dict:

        # delta based classification convention:
        # 0 = none or idle, 1 = positive, 2 = negative
        if self.delta_per_unit:
            current_median = segment["median_value"]
            if self._last_median is not None:
                inter_delta = current_median - self._last_median
                if inter_delta > self.delta_per_unit * 0.5:
                    label = self.mapping.get(1, "unknown")
                    cluster_id = 1
                elif inter_delta < -self.delta_per_unit * 0.5:
                    label = self.mapping.get(2, "unknown")
                    cluster_id = 2
                else:
                    label = self.mapping.get(0, "unknown")
                    cluster_id = 0
            else:
                label = self.mapping.get(0, "unknown")
                cluster_id = 0
            self._last_median = current_median
            segment["cluster_id"] = cluster_id
            segment["label"] = label

        else:
            cluster_id = self._nearest_cluster(segment)
            label = self.mapping.get(cluster_id, "unknown")
            segment["cluster_id"] = cluster_id
            segment["label"] = label

        if self._out_file:
            self._out_file.write(json.dumps(segment) + "\n")
            self._out_file.flush()

        if self.on_classified:
            self.on_classified(segment)

        return segment

    def close(self):

        if self._out_file:
            self._out_file.close()
            self._out_file = None


# standalone batch mode

if __name__ == "__main__":
    import sys

    logging.basicConfig(level=logging.INFO)

    segments_file = sys.argv[1] if len(sys.argv) > 1 else "segments.jsonl"
    thresholds_file = sys.argv[2] if len(sys.argv) > 2 else "thresholds.json"
    mapping_file = sys.argv[3] if len(sys.argv) > 3 else "cluster_activity_mapping.json"

    classifier = Classifier(thresholds_file, mapping_file)

    print(f"\nClassification of {segments_file}\n", file=sys.stderr)
    print(f"{'time':>10}  {'Cluster':>8}  {'Label':<20}  Case", file=sys.stderr)
    print("-" * 60, file=sys.stderr)

    with open(segments_file) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            seg = json.loads(line)
            classifier.classify(seg)

            t = seg["window_start"][11:19]
            case = seg.get("case_id", "-")
            print(
                f"{t:>10}  {seg['cluster_id']:>8}  {seg['label']:<20}  {case}",
                file=sys.stderr,
            )
            print(json.dumps(seg))

    classifier.close()
